import React, { useState } from 'react';
import { 
  Bot, 
  Check, 
  X, 
  Sparkles, 
  FileText, 
  Shield, 
  Zap 
} from 'lucide-react';

const AIDetectorLandingPage = () => {
  const [text, setText] = useState('');
  const [analysisResult, setAnalysisResult] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const exampleTexts = [
    {
      title: 'ChatGPT Generated',
      content: 'In the realm of digital innovation, artificial intelligence continues to push the boundaries of what is possible, transforming industries and reshaping our understanding of technological potential.',
      isAI: true
    },
    {
      title: 'Human Written',
      content: 'The morning sun crept through the window, casting long shadows across the worn wooden floor. My grandmother\'s antique clock ticked softly, a rhythm that had accompanied countless family stories.',
      isAI: false
    }
  ];

  const handleDetection = async () => {
    if (!text.trim()) {
      alert('Please enter some text to analyze');
      return;
    }

    setIsLoading(true);
    try {
      // Simulated detection logic
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      const aiProbability = Math.random();
      setAnalysisResult({
        isAI: aiProbability > 0.5,
        probability: (aiProbability * 100).toFixed(2)
      });
    } catch (error) {
      console.error('Detection error:', error);
      setAnalysisResult(null);
    } finally {
      setIsLoading(false);
    }
  };

  const handleExampleClick = (exampleText) => {
    setText(exampleText.content);
  };

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="container mx-auto px-4 py-16 max-w-6xl">
        {/* Header */}
        <header className="text-center mb-16">
          <div className="flex items-center justify-center mb-4">
            <Bot className="w-12 h-12 text-blue-600 mr-3" />
            <h1 className="text-4xl font-bold text-gray-800">
              AI Content Detector
            </h1>
          </div>
          <p className="text-gray-600 max-w-2xl mx-auto">
            Instantly detect whether your text was generated by AI or written by a human using our advanced machine learning algorithm.
          </p>
        </header>

        {/* Main Content */}
        <div className="grid md:grid-cols-2 gap-8">
          {/* Input Section */}
          <div className="bg-white rounded-xl p-6 shadow-lg border border-gray-200">
            <textarea 
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="Paste your text here to detect AI content..."
              className="w-full h-48 bg-gray-50 text-gray-800 rounded-lg p-4 border border-gray-300 focus:border-blue-500 transition-all duration-300 resize-none"
            />
            
            <div className="mt-4 flex space-x-4">
              <button 
                onClick={handleDetection}
                disabled={isLoading}
                className="flex-grow bg-blue-600 text-white py-3 rounded-lg 
                hover:bg-blue-700 transition-all duration-300 
                flex items-center justify-center disabled:opacity-50"
              >
                {isLoading ? 'Analyzing...' : 'Detect AI Content'}
              </button>
            </div>

            {/* Result Display */}
            {analysisResult && (
              <div className={`mt-4 p-4 rounded-lg ${analysisResult.isAI ? 'bg-red-50 border-red-200' : 'bg-green-50 border-green-200'} flex items-center border`}>
                {analysisResult.isAI ? (
                  <X className="text-red-500 mr-3" />
                ) : (
                  <Check className="text-green-500 mr-3" />
                )}
                <div>
                  <p className="font-semibold text-gray-800">
                    {analysisResult.isAI ? 'Likely AI Generated' : 'Likely Human Written'}
                  </p>
                  <p className="text-sm text-gray-600">
                    Probability: {analysisResult.probability}%
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* Examples Section */}
          <div>
            <h2 className="text-2xl font-bold mb-6 flex items-center text-gray-800">
              <Sparkles className="mr-3 text-yellow-500" />
              Example Texts
            </h2>
            <div className="space-y-4">
              {exampleTexts.map((example, index) => (
                <div 
                  key={index} 
                  onClick={() => handleExampleClick(example)}
                  className="bg-white rounded-lg p-4 cursor-pointer hover:bg-gray-100 transition-colors group border border-gray-200 shadow-sm"
                >
                  <div className="flex items-center mb-2">
                    {example.isAI ? (
                      <Bot className="mr-2 text-red-500" />
                    ) : (
                      <FileText className="mr-2 text-green-500" />
                    )}
                    <h3 className="font-semibold text-gray-800">{example.title}</h3>
                  </div>
                  <p className="text-gray-600 line-clamp-3">{example.content}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Features Section */}
        <section className="mt-16 grid md:grid-cols-3 gap-8 text-center">
          <div className="bg-white p-6 rounded-xl shadow-md border border-gray-200">
            <Shield className="mx-auto mb-4 text-blue-600 w-12 h-12" />
            <h3 className="font-bold text-xl mb-2 text-gray-800">Accurate Detection</h3>
            <p className="text-gray-600">Advanced machine learning models</p>
          </div>
          <div className="bg-white p-6 rounded-xl shadow-md border border-gray-200">
            <Zap className="mx-auto mb-4 text-green-600 w-12 h-12" />
            <h3 className="font-bold text-xl mb-2 text-gray-800">Instant Results</h3>
            <p className="text-gray-600">Get analysis in seconds</p>
          </div>
          <div className="bg-white p-6 rounded-xl shadow-md border border-gray-200">
            <FileText className="mx-auto mb-4 text-purple-600 w-12 h-12" />
            <h3 className="font-bold text-xl mb-2 text-gray-800">Multiple Formats</h3>
            <p className="text-gray-600">Support for various text types</p>
          </div>
        </section>
      </div>
    </div>
  );
};

export default AIDetectorLandingPage;